//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanoMessageBus.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Diagnostics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Diagnostics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NanoMessageBus.Core.Diagnostics", typeof(Diagnostics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing unit of work..
        /// </summary>
        internal static string CommittingUnitOfWork {
            get {
                return ResourceManager.GetString("CommittingUnitOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferring message to a later point..
        /// </summary>
        internal static string DeferringMessage {
            get {
                return ResourceManager.GetString("DeferringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing message receiver..
        /// </summary>
        internal static string DisposingMessageReceiver {
            get {
                return ResourceManager.GetString("DisposingMessageReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing transformations on message..
        /// </summary>
        internal static string PerformingTransformations {
            get {
                return ResourceManager.GetString("PerformingTransformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing message to configured handlers..
        /// </summary>
        internal static string RoutingMessagesToHandlers {
            get {
                return ResourceManager.GetString("RoutingMessagesToHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing message to handler of type &apos;{0}&apos;..
        /// </summary>
        internal static string RoutingMessageToHandler {
            get {
                return ResourceManager.GetString("RoutingMessageToHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping remaining handlers..
        /// </summary>
        internal static string SkippingRemainingHandlers {
            get {
                return ResourceManager.GetString("SkippingRemainingHandlers", resourceCulture);
            }
        }
    }
}
