//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanoMessageBus.SubscriptionStorage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlStatements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlStatements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NanoMessageBus.SubscriptionStorage.SqlStatements", typeof(SqlStatements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///  FROM Subscriptions
        ///   AND Subscriber = @subscriber
        ///   AND MessageType = @messageType;.
        /// </summary>
        internal static string DeleteSubscription {
            get {
                return ResourceManager.GetString("DeleteSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @expiration.
        /// </summary>
        internal static string ExpirationParameter {
            get {
                return ResourceManager.GetString("ExpirationParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Subscriber
        ///  FROM Subscriptions
        /// WHERE Expiration &gt; @now
        ///   AND MessageType IN (&apos;&apos;{0});.
        /// </summary>
        internal static string GetSubscribers {
            get {
                return ResourceManager.GetString("GetSubscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///  FROM Subscriptions
        ///   AND Subscriber = @subscriber
        ///   AND MessageType = @messageType
        ///
        ///INSERT
        ///  INTO Subscriptions
        ///     ( Subscriber, MessageType, Expiration )
        ///SELECT @subscriber, @messageType, @expiration;.
        /// </summary>
        internal static string InsertSubscription {
            get {
                return ResourceManager.GetString("InsertSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @messageType.
        /// </summary>
        internal static string MessageTypeParameter {
            get {
                return ResourceManager.GetString("MessageTypeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , @messageType{0}.
        /// </summary>
        internal static string MessageTypeWhereParameter {
            get {
                return ResourceManager.GetString("MessageTypeWhereParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @now.
        /// </summary>
        internal static string NowParameter {
            get {
                return ResourceManager.GetString("NowParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @subscriber.
        /// </summary>
        internal static string SubscriberParameter {
            get {
                return ResourceManager.GetString("SubscriberParameter", resourceCulture);
            }
        }
    }
}
