//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanoMessageBus.Transports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TransportDiagnostics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransportDiagnostics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NanoMessageBus.Transports.TransportDiagnostics", typeof(TransportDiagnostics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker thread &apos;{0}&apos; received a message; dispatching the message to receiver of type &apos;{1}&apos;..
        /// </summary>
        internal static string DispatchingToReceiver {
            get {
                return ResourceManager.GetString("DispatchingToReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing transport..
        /// </summary>
        internal static string DisposingTransport {
            get {
                return ResourceManager.GetString("DisposingTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing {0} worker threads..
        /// </summary>
        internal static string InitializingWorkers {
            get {
                return ResourceManager.GetString("InitializingWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker thread &apos;{0}&apos; has processed the message successfully..
        /// </summary>
        internal static string MessageProcessed {
            get {
                return ResourceManager.GetString("MessageProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending a message to the endpoint..
        /// </summary>
        internal static string SendingMessage {
            get {
                return ResourceManager.GetString("SendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker thread &apos;{0}&apos; is starting execution and awaiting new work..
        /// </summary>
        internal static string StartingWorker {
            get {
                return ResourceManager.GetString("StartingWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker thread &apos;{0}&apos; is stopping executing of new work..
        /// </summary>
        internal static string StoppingWorker {
            get {
                return ResourceManager.GetString("StoppingWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping all {0} worker threads..
        /// </summary>
        internal static string StoppingWorkers {
            get {
                return ResourceManager.GetString("StoppingWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker {0}.
        /// </summary>
        internal static string WorkerThreadName {
            get {
                return ResourceManager.GetString("WorkerThreadName", resourceCulture);
            }
        }
    }
}
